apiVersion: v1
kind: PersistentVolume
metadata:
  name: csgo-storage-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  awsElasticBlockStore:
    volumeID: vol-013163644de6dee50
    fsType: ext4
