apiVersion: v1
kind: PersistentVolume
metadata:
  name: csgo-storage-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  awsElasticBlockStore:
    volumeID: vol-079f442b62221b0d4
    fsType: ext4
