apiVersion: v1
type: Opaque
data:
  SRCDS_TOKEN: {{SRCDS_TOKEN}}
kind: Secret
metadata:
  name: steam-token
  namespace: {{APP_ENV}}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: csgo-deployment-{{APP_ENV}}
  name: csgo-deployment
  namespace: {{APP_ENV}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csgo-deployment-{{APP_ENV}}
  template:
    metadata:
      labels:
        app: csgo-deployment-{{APP_ENV}}
    spec:
      containers:
      - image: {{SERVER_IMAGE}}
        name: csgo-server-{{APP_ENV}}
        ports:
        - containerPort: 27015
          protocol: UDP
        env:
          - name: SRCDS_TOKEN
            valueFrom:
              secretKeyRef:
                name: steam-token
                key: SRCDS_TOKEN
        volumeMounts:
        - name: csgo-configuration-server-cfg
          mountPath: /etc/server.cfg
          subPath: server.cfg

        - name: csgo-configuration-autoexec-cfg
          mountPath: /etc/autoexec.cfg
          subPath: autoexec.cfg

      volumes:
        - name: csgo-configuration-server-cfg
          configMap:
            name: csgo-configuration
            items:
            - key: server.cfg
              path: server.cfg

        - name: csgo-configuration-autoexec-cfg
          configMap:
            name: csgo-configuration
            items:
            - key: autoexec.cfg
              path: autoexec.cfg
