apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: csgods-{{APP_ENV}}
  name: csgods
  namespace: {{APP_ENV}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csgods-{{APP_ENV}}
  template:
    metadata:
      labels:
        app: csgods-{{APP_ENV}}
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - image: {{SERVER_IMAGE}}
        name: csgo-server-{{APP_ENV}}
        command:
          - /bin/bash
          - -c
          - chmod u+x /home/steam/entry.sh && ./entry.sh
        ports:
        - containerPort: 27015
          protocol: TCP
        env:
          - name: SRCDS_TOKEN
            valueFrom:
              secretKeyRef:
                name: steam-token
                key: SRCDS_TO1KEN
        volumeMounts:
        - name: csgo-configuration-server-cfg
          mountPath: /etc/server.cfg
          subPath: server.cfg

        - name: csgo-configuration-autoexec-cfg
          mountPath: /etc/autoexec.cfg
          subPath: autoexec.cfg

      volumes:
        - name: csgo-configuration-server-cfg
          configMap:
            name: csgo-configuration
            items:
            - key: server.cfg
              path: server.cfg

        - name: csgo-configuration-autoexec-cfg
          configMap:
            name: csgo-configuration
            items:
            - key: autoexec.cfg
              path: autoexec.cfg
