apiVersion: v1
kind: Service
metadata:
  labels:
    app: csgo
  name: csgo-svc
  namespace: yf-csgo-server
spec:
  ports:
  - name: steam
    port: 27015
    protocol: UDP
    targetPort: 27015
    nodePort: 30001
  selector:
    app: csgods-yf-csgo-server
  type: NodePort

